# Use java
language: java

# Don't need super user
sudo: false

# Add PostgreSQL database
services:
  - postgresql

addons:
  postgresql: "9.6"

# Create testing database
before_script:
  # Create usual database
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER tester WITH PASSWORD 'password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test_db TO tester;" -U postgres
  # Create liquibase database
  - psql -c "CREATE DATABASE liquid_test" -U postgres

# Code coverage count after successful build
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Notification if build failed.
notifications:
  email:
    recipients:
      - vermucht@gmail.com
on_success: never   # default: change
on_failure: change  # default: always