# Use java
language: java

# Don't need super user
sudo: false

# Add PostgreSQL database
services:
- postgresql

addons:
  postgresql: "9.4"

# Create testing database
before_script:
- psql -c "CREATE DATABASE test_db;" -U postgres
- psql -c "CREATE USER tester WITH PASSWORD 'password';" -U postgres -d test_db

# Code coverage count after successful build
after_success:
- bash <(curl -s https://codecov.io/bash)

# Notification if build failed.
notifications:
  email:
    recipients:
    - vermucht@gmail.com
    on_success: never   # default: change
on_failure: always      # default: always