# Use java language
language: java

# We don't need super user
sudo: false

# Add PostgreSQL database
services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'password';" -U postgres

# Launch JaCoCo statistics after build. Here we use service from https://codecov.io/
  after_success:
    - bash <(curl -s https://codecov.io/bash)

# Send email if build failed
notifications:
  email:
    recipients:
      - vermucht@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

